syntax = "proto3";

package cloudteams;

option go_package = "pkg/api/cloudteams";

message AgentActivity {
  // message sent by agent, either as a response to a command or an event from enabled sources
  Message message = 2;
}

enum MessageType {
  MESSAGE_TYPE_MESSAGE_EXECUTOR_UNSPECIFIED = 0;
  MESSAGE_TYPE_MESSAGE_SOURCE = 1;
}

message Message {
  string team_id = 1;
  string conversation_id = 3;
  MessageType message_type = 4;
  bytes data = 5;
}

message CloudActivity {
  bytes event = 1;
  string conversation_display_name = 2;
}

service CloudTeams {
  rpc StreamActivity(stream AgentActivity) returns (stream CloudActivity) {}
}
