name: Branch build

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-e2e-tests]

env:
  HELM_VERSION: v3.9.0
  K3D_VERSION: v5.4.6
  IMAGE_REGISTRY: "ghcr.io"
  IMAGE_REPOSITORY: "iggy/botkube"
  CFG_EXPORTER_IMAGE_REPOSITORY: "iggy/botkube-config-exporter"
  IMAGE_TAG: v9.99.9-dev # TODO: Use commit hash tag to make the predictable builds for each commit on branch
  GIT_USER: botkube-dev

jobs:
  extract-metadata:
    if: github.event_name != 'repository_dispatch' # skip if triggered by repository_dispatch
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.extract-version.outputs.versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Extract version
        id: extract-version
        run: |
          IMAGE_VERSION=$(git rev-parse --short HEAD)
          echo "versions={\"image-version\":[\"v9.99.9-dev\",\"0.0.0-${IMAGE_VERSION}\"]}" >> "$GITHUB_OUTPUT"
  build:
    if: github.event_name != 'repository_dispatch' # skip if triggered by repository_dispatch
    needs: [extract-metadata]
    strategy:
      matrix: ${{ fromJson(needs.extract-metadata.outputs.versions) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GO111MODULE: on
      GOPATH: /home/runner/work/botkube
      GOBIN: /home/runner/work/botkube/bin
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Docker Login
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          install-only: true
          version: latest
      - name: Run GoReleaser
        run: |
          make release-snapshot
        env:
          GORELEASER_CURRENT_TAG: ${{ matrix.image-version }}
          IMAGE_TAG: ${{ matrix.image-version }}
